# Generated by Django 3.1.5 on 2021-10-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Note',
        ),
        migrations.AddField(
            model_name='food',
            name='notes',
            field=models.ManyToManyField(to='testapp.Note'),
        ),
    ]
