#!/bin/sh

set -e

cd $(dirname $0)
cd ..

if [ ! -e /.dockerenv ]; then
    # not in container
    .jenkins/run_tests
    docker run -v $(pwd):/work \
               -w /work \
               -e ARTIFACTORY_USER \
               -e ARTIFACTORY_PASSWORD \
               docker.app.betfair/appsec/base/python:3.9-slim-buster \
               /work/.jenkins/ci_build
    exit 0
fi

export TWINE_USERNAME=${ARTIFACTORY_USER}
export TWINE_PASSWORD=${ARTIFACTORY_PASSWORD}
export TWINE_NON_INTERACTIVE=1

# check if package-version already uploaded (pypi.org blocks but ppb artifactory does not)
PN=$(python setup.py --name)
PV=$(python setup.py --version)
# requests required by twine anyway, not a waste :)
pip install 'requests<3'
python <<EOF
import requests, sys
c=requests.get('https://artifactory-prd.prd.betfair/artifactory/api/pypi/pypi/$PN/$PV/').status_code
if c != 404:
  print(f'ERROR: version already exists? [{c}]', file=sys.stderr)
  exit(2)
EOF

pip install twine


python setup.py sdist
python -m twine upload --repository-url https://artifactory-prd.prd.betfair/artifactory/api/pypi/pypi dist/*
